Repository d-h-k/issue-tracker, pull requests merged in 2021-06, with the labels that each got.

#11 FilterButton, FilterInput
  FE/package-lock.json
  FE/package.json
  FE/src/App.css
  FE/src/App.tsx
  FE/src/components/IssueList/Filter.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/Root.tsx
  FE/src/config/GlobalStyle.tsx
  FE/src/index.css
  FE/tsconfig.json
Labels: FE

#23 [iOS] 로그인 UI 구성
  BE/README.md
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Assets.xcassets/BackGround.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Border.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/CloseCarrot.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/DeleteSunnyside.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/MainGrape.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/OpenBrocoli.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_apple.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_apple.imageset/icon_apple.png
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_github.imageset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/icon_github.imageset/icon_github.png
  iOS/issue-tracker/issue-tracker/Base.lproj/Main.storyboard
  iOS/issue-tracker/issue-tracker/Common/Colors.swift
  iOS/issue-tracker/issue-tracker/Common/UIImageExtension.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/ViewController.swift
Labels: feature, iOS

#24 [iOS] 이슈 트래커 탭바 흐름 생성
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Common/UIViewControllerExtension.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
Labels: feature, iOS

#25 IssueList 구현
  FE/src/components/IssueList/Controller/AddButton.tsx
  FE/src/components/IssueList/Controller/Controller.tsx
  FE/src/components/IssueList/Controller/Tabs.tsx
  FE/src/components/IssueList/Filter.tsx
  FE/src/components/IssueList/Filter/Filter.tsx
  FE/src/components/IssueList/Filter/FilterButton.tsx
  FE/src/components/IssueList/Filter/FilterInput.tsx
  FE/src/components/IssueList/Filter/FilterPopUp.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/IssueList/List/Header.tsx
  FE/src/components/IssueList/List/Issue.tsx
  FE/src/components/IssueList/List/List.tsx
Labels: FE

#28 Label
  FE/src/components/IssueList/List/Issue.tsx
  FE/src/components/IssueList/List/List.tsx
  FE/src/components/common/Label.tsx
Labels: FE

#33 NewIssue, SideBar(일부)
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/NewIssue/Content.tsx
  FE/src/components/NewIssue/NewIssue.tsx
  FE/src/components/common/SideBar.tsx
Labels: FE

#38 [iOS] 애플 소셜로그인 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Common/AlertFactory.swift
  iOS/issue-tracker/issue-tracker/LifeCycle/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/AppleAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/AppleLoginManagerDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/LoginError.swift
  iOS/issue-tracker/issue-tracker/Login/LoginInfo.swift
  iOS/issue-tracker/issue-tracker/Login/LoginKeyChainManager.swift
  iOS/issue-tracker/issue-tracker/Login/LoginService.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/LoginInfoContainer.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
  iOS/issue-tracker/issue-tracker/issue-tracker.entitlements
Labels: feature, iOS

#47 LabelList 구현
  FE/src/atoms/atoms.tsx
  FE/src/components/IssueList/Controller/Controller.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/LabelList/Label.tsx
  FE/src/components/LabelList/LabelList.tsx
  FE/src/components/LabelList/LabelModal.tsx
  FE/src/components/LabelList/List.tsx
  FE/src/components/Root.tsx
  FE/src/components/common/AddButton.tsx
  FE/src/components/common/Label.tsx
  FE/src/components/common/Tabs.tsx
Labels: FE

#49 Refactor
  FE/src/atoms/atoms.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/Login/Callback.tsx
  FE/src/components/Root.tsx
Labels: FE

#46 [iOS] 소셜로그인 리팩토링
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/issue-tracker/issue-tracker/LifeCycle/AppDelegate.swift
  iOS/issue-tracker/issue-tracker/LifeCycle/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/AppleLoginManagerDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Apple/AppleAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/GithubAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/OAuthResponseDTO.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginError.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginInfo.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginKeyChainManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginService.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Protocol/SocialLoginManagable.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Protocol/SocialLoginManagerDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarCreator.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/TabBarChildInfo.swift
  iOS/issue-tracker/issue-tracker/Network/ImageLoadManager.swift
  iOS/issue-tracker/issue-tracker/Network/NetworkManager.swift
Labels: iOS, refactor

#54 [BE] GitHub Oauth기능 구현
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/codesquad/issueTracker/config/WebConfig.java
  BE/src/main/java/codesquad/issueTracker/domain/User.java
  BE/src/main/java/codesquad/issueTracker/oauth/OauthController.java
  BE/src/main/java/codesquad/issueTracker/oauth/dto/GithubAccessTokenRequest.java
  BE/src/main/java/codesquad/issueTracker/oauth/dto/GithubAccessTokenResponse.java
  BE/src/main/java/codesquad/issueTracker/oauth/dto/OauthDTO.java
  BE/src/main/java/codesquad/issueTracker/oauth/dto/OauthJwt.java
  BE/src/main/java/codesquad/issueTracker/oauth/dto/OauthUser.java
  BE/src/main/java/codesquad/issueTracker/oauth/exception/BadRequest.java
  BE/src/main/java/codesquad/issueTracker/oauth/exception/NoAuthorizationException.java
  BE/src/main/java/codesquad/issueTracker/oauth/interceptor/OauthInterceptor.java
  BE/src/main/java/codesquad/issueTracker/oauth/service/JwtUtils.java
  BE/src/main/java/codesquad/issueTracker/oauth/service/OauthService.java
  BE/src/main/java/codesquad/issueTracker/repository/UserRepository.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
Labels: BE, feature

#57 IssueDeatil 구현
  FE/src/atoms/atoms.tsx
  FE/src/components/DetailIssue/Comment.tsx
  FE/src/components/DetailIssue/CommentModal.tsx
  FE/src/components/DetailIssue/DetailIssue.tsx
  FE/src/components/DetailIssue/Header.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/IssueList/List/Issue.tsx
  FE/src/components/IssueList/List/List.tsx
  FE/src/components/Root.tsx
  FE/src/components/common/AddButton.tsx
  FE/src/components/common/SideBar.tsx
Labels: FE

#61 [BE] Label API 기능 추가
  BE/src/main/java/codesquad/issueTracker/Data.java
  BE/src/main/java/codesquad/issueTracker/controller/LabelController.java
  BE/src/main/java/codesquad/issueTracker/domain/Label.java
  BE/src/main/java/codesquad/issueTracker/repository/LabelRepository.java
  BE/src/main/java/codesquad/issueTracker/service/LabelService.java
Labels: BE, feature

#60 Fe/feature/login refactor
  FE/src/atoms/atoms.tsx
  FE/src/components/Error/NotFound.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/Header/HeaderModal.tsx
  FE/src/components/IssueList/IssueList.tsx
  FE/src/components/Login/AuthRoute.tsx
  FE/src/components/Login/Callback.tsx
  FE/src/components/Login/Login.tsx
  FE/src/components/Root.tsx
  FE/src/components/common/Modal.jsx
Labels: FE

#65 [BE] milestone API 구현
  BE/.gitignore
  BE/src/main/java/codesquad/issueTracker/config/WebConfig.java
  BE/src/main/java/codesquad/issueTracker/controller/MilestoneController.java
  BE/src/main/java/codesquad/issueTracker/domain/Milestone.java
  BE/src/main/java/codesquad/issueTracker/repository/MilestoneRepository.java
  BE/src/main/java/codesquad/issueTracker/service/MilestoneService.java
  BE/src/main/resources/application.properties
Labels: BE, feature

#66 [iOS] PR 보내기 전 추가 커밋 로그아웃 + 프로필화면
  iOS/issue-tracker/issue-tracker/Common/Colors.swift
  iOS/issue-tracker/issue-tracker/LifeCycle/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Apple/AppleAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/GithubAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/OAuthResponseDTO.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarCreator.swift
Labels: feature, iOS

#67 Label CRUD API 적용
  FE/src/atoms/atoms.tsx
  FE/src/components/LabelList/Label.tsx
  FE/src/components/LabelList/LabelList.tsx
  FE/src/components/LabelList/LabelModal.tsx
  FE/src/components/common/Label.tsx
Labels: FE

#84 [iOS] 레이블 씬 생성 / View 재사용성 확보
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Common/UITextFieldExtension.swift
  iOS/issue-tracker/issue-tracker/LifeCycle/SceneDelegate.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Apple/AppleAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/GithubAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/JWT.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/OAuthResponseDTO.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginError.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginInfo.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginInfoDTO.swift
  iOS/issue-tracker/issue-tracker/Login/Model/LoginKeyChainManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Protocol/SocialLoginManagerDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Common/CellAction.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/ImageBarButton.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/LabelView.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/MultipleLineInputStackView.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/TopMenuView.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelControlViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelTableViewDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/HexColorCode.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/HexColorConvertable.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/HexColorConverter.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/Label.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/NewLabelDTO.swift
  iOS/issue-tracker/issue-tracker/Main/Label/View/LabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/LoginInfoContainer.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/MilestoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarCreator.swift
  iOS/issue-tracker/issue-tracker/Network/EndPoint.swift
  iOS/issue-tracker/issue-tracker/Network/NetworkError.swift
  iOS/issue-tracker/issue-tracker/Network/NetworkManager.swift
  iOS/issue-tracker/issue-tracker/Network/RequestKeys.swift
  iOS/issue-tracker/issue-tracker/Network/RequestManager.swift
Labels: feature, iOS, refactor

#83 [iOS] 마일스톤 구현
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Assets.xcassets/Description.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/MileStoneSuccess.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/OpenMileStoneBG.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/closeMileStoneBG.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/closeMileStoneTint.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/openMileStoneTint.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Common/Colors.swift
  iOS/issue-tracker/issue-tracker/Common/String.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/GithubAuthorizationManager.swift
  iOS/issue-tracker/issue-tracker/Login/Model/Github/OAuthResponseDTO.swift
  iOS/issue-tracker/issue-tracker/Main/Common/CommonTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/MultipleLineInputStackView.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MileStoneControlViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MileStoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MilestoneTableViewDataSource.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/MileStoneLabelView.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/Milestone.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/NewMileStoneDTO.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/View/MileStoneTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/MyAccount/MyAccountViewController.swift
  iOS/issue-tracker/issue-tracker/Main/TabBar/IssueTrackerTabBarCreator.swift
  iOS/issue-tracker/issue-tracker/Network/NetworkManager.swift
Labels: feature, iOS

#87 미구현 기능 추가
  FE/src/atoms/atoms.tsx
  FE/src/components/DetailIssue/Comment.tsx
  FE/src/components/DetailIssue/CommentModal.tsx
  FE/src/components/DetailIssue/DetailIssue.tsx
  FE/src/components/DetailIssue/Header.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/Header/HeaderModal.tsx
  FE/src/components/IssueList/Filter/Filter.tsx
  FE/src/components/IssueList/Filter/FilterInput.tsx
  FE/src/components/IssueList/Filter/FilterPopUp.tsx
  FE/src/components/IssueList/List/Header.tsx
  FE/src/components/IssueList/List/Issue.tsx
  FE/src/components/IssueList/List/List.tsx
  FE/src/components/LabelList/LabelModal.tsx
  FE/src/components/Login/Callback.tsx
  FE/src/components/NewIssue/Content.tsx
  FE/src/components/NewIssue/NewIssue.tsx
  FE/src/components/Root.tsx
  FE/src/components/common/Label.tsx
  FE/src/components/common/SideBar.tsx
  FE/src/config/interface.ts
Labels: FE

#89 [BE] Issue 기본 CRUD 생성
  BE/build.gradle
  BE/src/main/java/codesquad/issueTracker/ApiResult.java
  BE/src/main/java/codesquad/issueTracker/Data.java
  BE/src/main/java/codesquad/issueTracker/config/WebConfig.java
  BE/src/main/java/codesquad/issueTracker/controller/CommentController.java
  BE/src/main/java/codesquad/issueTracker/controller/IssueController.java
  BE/src/main/java/codesquad/issueTracker/controller/LabelController.java
  BE/src/main/java/codesquad/issueTracker/controller/MilestoneController.java
  BE/src/main/java/codesquad/issueTracker/domain/Comment.java
  BE/src/main/java/codesquad/issueTracker/domain/Issue.java
  BE/src/main/java/codesquad/issueTracker/domain/IssueAssignee.java
  BE/src/main/java/codesquad/issueTracker/domain/IssueHasLabel.java
  BE/src/main/java/codesquad/issueTracker/domain/Label.java
  BE/src/main/java/codesquad/issueTracker/domain/Milestone.java
  BE/src/main/java/codesquad/issueTracker/domain/User.java
  BE/src/main/java/codesquad/issueTracker/domain/compositeKey/IssueAssigneeId.java
  BE/src/main/java/codesquad/issueTracker/domain/compositeKey/IssueHasLabelId.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueAssigneeIdsRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueHasLabelIdsRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueIdsRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueMilestoneRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/request/IssueTitleRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/DefaultIssueResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/IssueDetailMilestoneResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/IssueDetailResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/IssueLabelResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/IssueMilestoneResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/issue/response/IssueResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/request/CommentRequest.java
  BE/src/main/java/codesquad/issueTracker/dto/response/CommentResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/response/DetailMilestoneResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/response/LabelResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/response/MilestoneResponse.java
  BE/src/main/java/codesquad/issueTracker/dto/response/UserResponse.java
  BE/src/main/java/codesquad/issueTracker/oauth/UserArgumentResolver.java
  BE/src/main/java/codesquad/issueTracker/oauth/annotation/LoginRequired.java
  BE/src/main/java/codesquad/issueTracker/oauth/annotation/UserId.java
  BE/src/main/java/codesquad/issueTracker/oauth/interceptor/OauthInterceptor.java
  BE/src/main/java/codesquad/issueTracker/oauth/service/JwtUtils.java
  BE/src/main/java/codesquad/issueTracker/repository/CommentRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/IssueAssigneeRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/IssueHasLabelRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/IssueRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/LabelRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/MilestoneRepository.java
  BE/src/main/java/codesquad/issueTracker/repository/UserRepository.java
  BE/src/main/java/codesquad/issueTracker/service/CommentService.java
  BE/src/main/java/codesquad/issueTracker/service/IssueService.java
  BE/src/main/java/codesquad/issueTracker/service/LabelService.java
  BE/src/main/java/codesquad/issueTracker/service/MilestoneService.java
  BE/src/main/java/codesquad/issueTracker/service/UserService.java
Labels: BE, feature

#97 [iOS] Issues 보여주기 화면 구성
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Assets.xcassets/AddIssueBtn.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueDetailViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueTableViewDataSource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Model/Issue.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelTableViewDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/Label.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MileStoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MilestoneTableViewDataSource.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/Milestone.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/NewMileStoneDTO.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/View/MileStoneTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Network/EndPoint.swift
Labels: feature, iOS

#98 [iOS] 이슈 작성 화면
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/issue-tracker/issue-tracker/Assets.xcassets/CloseMileStoneBG.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/CloseMileStoneTint.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Assets.xcassets/OpenMileStoneTint.colorset/Contents.json
  iOS/issue-tracker/issue-tracker/Common/UITableCellExtension.swift
  iOS/issue-tracker/issue-tracker/Main/Common/CommonDTO.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/ImageBarButton.swift
  iOS/issue-tracker/issue-tracker/Main/Common/View/MultipleLineInputStackView.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/AdditionalInfoViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/CellSelectionTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/IssueControlViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/Protocol/SimpleInfoTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/Protocol/SimpleInfoTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleAssigneeTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleLabelTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleMilestoneTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueTableViewDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Model/User.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/IssueInfoView.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/SimpleAssigneeTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/SimpleLabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/SimpleMilestoneTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Model/Label.swift
  iOS/issue-tracker/issue-tracker/Main/Label/View/LabelTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MileStoneViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Model/Milestone.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/View/MileStoneTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Network/EndPoint.swift
Labels: feature, iOS

#99 [iOS] 새 이슈 POST + 리팩토링
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/AdditionalInfoViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/CellSelectionTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/CommonInfoTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/IssueEditViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/IssueViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/Protocol/AdditionalInfoTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/Protocol/AdditionalInfoTableDelegate.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/Protocol/SimpleInfoTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleAssigneeTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleLabelTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/SimpleMilestoneTableDatasource.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Model/NewIssue.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/AssigneeInfoTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/LabelInfoTableViewCell.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/View/IssueEditing/MilestoneInfoTableViewCell.swift
Labels: feature, iOS, refactor

#112 [iOS] 키보드 dismiss
  iOS/issue-tracker/issue-tracker.xcodeproj/project.pbxproj
  iOS/issue-tracker/issue-tracker/Common/UIViewControllerExtension.swift
  iOS/issue-tracker/issue-tracker/Login/Controller/LoginViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/AdditionalInfoViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Issue/Controller/IssueEditing/IssueEditViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Label/Controller/LabelControlViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/MileStoneControlViewController.swift
  iOS/issue-tracker/issue-tracker/Main/Milestone/Controller/OrderedTextFieldDelgate.swift
Labels: iOS
